# generated by datamodel-codegen:
#   filename:  address.json
#   timestamp: 2026-04-11T16:27:14+00:00

from __future__ import annotations

from pydantic import BaseModel


class Address1(BaseModel):
    coOwnershipName: str
    floor: str
    number: str
    address: str


class Address(BaseModel):
    housingId: str
    name: str
    entryDate: str
    surface: int
    numberInhabitants: int
    housingType: str
    energyLabel: str
    company: str
    proofStatus: str
    isActive: bool
    proofUploadDate: str
    createdAt: str
    address: Address1
