# generated by datamodel-codegen:
#   filename:  auth.json
#   timestamp: 2026-04-11T16:27:11+00:00

from __future__ import annotations

from pydantic import BaseModel


class ConsumptionGoal(BaseModel):
    name: str
    value: str


class User(BaseModel):
    email: str
    password: str
    cgu: bool
    cgdatadaily: bool
    firstname: str
    lastname: str
    cgAcceptedAt: str
    lastConnected: None
    isActive: bool
    mobileNotification: bool
    emailNotification: bool
    consumptionGoal: ConsumptionGoal
    isOnboarded: bool
    roles: list[str]
    userIdentifier: str
    id: int
    userDeviceTokens: list[str]
    housingIds: list[str]
    housingNames: list[str]
    passwordResetCode: None
    passwordResetLimitDate: None
    createdAt: str
    updatedAt: str


class Auth(BaseModel):
    token: str
    refresh_token: str
    user: User
    housing: str
    company: str
