# generated by datamodel-codegen:
#   filename:  consumption_waterHot.json
#   timestamp: 2026-04-11T16:27:16+00:00

from __future__ import annotations

from pydantic import BaseModel


class Consumption1(BaseModel):
    date: str
    value: float
    minValue: float
    maxValue: float
    weightedValue: float


class Consumption(BaseModel):
    consumptions: list[Consumption1]
