# generated by datamodel-codegen:
#   filename:  consumption_waterHot.json
#   timestamp: 2026-04-11T16:27:16+00:00

from __future__ import annotations

from pydantic import BaseModel


class Consumption1(BaseModel):
    date: str | None = None
    value: float | None = None
    minValue: float | None = None
    maxValue: float | None = None
    weightedValue: float | None = None


class Consumption(BaseModel):
    consumptions: list[Consumption1]
