# generated by datamodel-codegen:
#   filename:  counters.json
#   timestamp: 2026-04-11T16:27:15+00:00

from __future__ import annotations

from pydantic import BaseModel, RootModel


class CounterItem(BaseModel):
    counter: str
    fluidType: str
    meterType: str
    unit: str
    housing: str


class Counter(RootModel[list[CounterItem]]):
    root: list[CounterItem]
