# generated by datamodel-codegen:
#   filename:  dashboard.json
#   timestamp: 2026-04-11T16:27:12+00:00

from __future__ import annotations

from pydantic import BaseModel


class Value(BaseModel):
    meterType: str
    fluidType: str
    unit: str
    value: float
    weightedValue: float | None
    minValue: float
    maxValue: float
    counters: list[str]


class CurrentMonth(BaseModel):
    startDate: str
    endDate: str
    values: list[Value]


class LastMonth(BaseModel):
    startDate: str
    endDate: str
    values: list[Value]


class Dashboard(BaseModel):
    currentMonth: CurrentMonth
    lastMonth: LastMonth
