# generated by datamodel-codegen:
#   filename:  housing.json
#   timestamp: 2026-04-11T16:27:14+00:00

from __future__ import annotations

from pydantic import BaseModel


class Housing(BaseModel):
    housingId: str
    name: str
    entryDate: str
    surface: int
    numberInhabitants: int
    housingType: str
    energyLabel: str
    company: str
    proofStatus: str
    isActive: bool
    proofUploadDate: str
    createdAt: str
