# generated by datamodel-codegen:
#   filename:  housings.json
#   timestamp: 2026-04-11T16:27:13+00:00

from __future__ import annotations

from pydantic import BaseModel


class MemberItem(BaseModel):
    field_id: str
    field_type: str
    housingId: str
    name: str
    created_date: str
    proofStatus: str


class Housings(BaseModel):
    totalItems: int
    member: list[MemberItem]
