# generated by datamodel-codegen:
#   filename:  meter_info.json
#   timestamp: 2026-04-11T16:27:16+00:00

from __future__ import annotations

from pydantic import BaseModel


class MeterInfo(BaseModel):
    location: str
    lastValue: str
    isDataOutdated: bool
