# generated by datamodel-codegen:
#   filename:  meter.json
#   timestamp: 2026-04-11T16:27:17+00:00

from __future__ import annotations

from pydantic import BaseModel


class Index(BaseModel):
    date: str
    value: float
    fluidType: str
    weightedValue: float | None


class Meter(BaseModel):
    indexes: list[Index]
