# generated by datamodel-codegen:
#   filename:  user.json
#   timestamp: 2026-04-11T16:27:13+00:00

from __future__ import annotations

from pydantic import BaseModel


class User(BaseModel):
    id: str
    firstname: str
    lastname: str
    isActive: bool
    isOnboarded: bool
    emailNotification: bool
    mobileNotification: bool
    consumptionGoal: str
